site_name: JDA-Boot Documentation
site_description: JDA-Boot is an annotation-driven JDA framework that lets you create bots insanely fast
repo_name: JDA-Boot
repo_url: https://github.com/swiftbytegbr/jda-boot/
site_url: https://jda-boot.swiftbyte.de/

nav:
  - Home: index.md
  - Getting Started: nav/getting-started.md
  - Interactions:
    - Commands: nav/commands.md
    - Buttons: nav/buttons.md
    - Select Menus: nav/select-menus.md
    - Modals: nav/modals.md
  - Embeds: nav/embeds.md
  - Events: nav/events.md
  - Translation and Configuration: nav/translation-configuration.md
  - Scheduler: nav/scheduler.md

theme:
    name: material
    features:
    - content.tabs.link
    - content.code.copy
    - toc.integrate
    - navigation.expand
    - navigation.footer

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.details